<?php
/**
 * 
 * Code skeleton generated by dia-uml2php5 plugin
 * written by KDO kdo@zpmag.com
 * @see        Personnage
 */
require_once('Personnage.class.php');

class Brute extends Personnage {


	/**
	 * @access public
	 * @param Personnage $perso 
	 * @return int
	 */

	public final  function frapper(Personnage $perso) {
	//ERROR: METHOD CAN'T BE OVERLOADED, PARENT HAS DECLARED IT 'final'!
	}


	/**
	 * @access public
	 * @return void
	 */

	public final  function gagnerExperience() {
	//ERROR: METHOD CAN'T BE OVERLOADED, PARENT HAS DECLARED IT 'final'!
	}


}
?>