<?php
/**
 * 
 * Code skeleton generated by dia-uml2php5 plugin
 * written by KDO kdo@zpmag.com
 */

class PersonnagesManager {

	/**
	 * Connexion BDD
	 * @var PDO
	 * @access protected
	 */
	protected  $db;


	/**
	 * Constructeur
	 * @access public
	 * @param PDO $db 
	 * @return void
	 */

	public final  function __construct(PDO $db) {

	}


	/**
	 * Méthode pour ajouter un personnage
	 * @access public
	 * @param Personnage $perso 
	 * @return void
	 */

	public final  function add(Personnage $perso) {

	}


	/**
	 * Compter le nombre de personnages créés
	 * @access public
	 * @return int
	 */

	public final  function count() {

	}


	/**
	 * Supprimer un personnage
	 * @access public
	 * @param Personnage $perso 
	 * @return void
	 */

	public final  function delete(Personnage $perso) {

	}


	/**
	 * Vérifier si personnage existe déjà
	 * @access public
	 * @param int|string $info 
	 * @return bool
	 */

	public final  function exists(int $info) {

	}


	/**
	 * Récupérer caractéristiques d'un personnage
	 * @access public
	 * @param int|string $info 
	 * @return Personnage
	 */

	public final  function get(string $info) {

	}


	/**
	 * Liste des personnages
	 * @access public
	 * @param string $nom 
	 * @return array
	 */

	public final  function getList($nom) {

	}


	/**
	 * Mettre à jour un personnage
	 * @access public
	 * @param Personnage $perso 
	 * @return void
	 */

	public final  function update(Personnage $perso) {

	}


}
?>